### ISSUE TITLE
How did you symlink the .env file?

### ISSUE THREAD

**Issue by idkjs** [Volst/new-food-order#20]
Never seen that before. Thanks for sharing this project.

**Comment by SpaceK33z** [comment]
Thanks!

E.g. for the `backend/.env` symlink, assuming the actual `.env` is in the root folder of the repository:

```bash
cd backend && ln -s ../.env .env
```

It's not a very great solution though, and it will not work on Windows (I think!). Optimally you can just use a commannd like `--dotenv=../.env`, but in the past Prisma had some issues with this (maybe this has been fixed).

**Comment by idkjs** [comment]
Damn. Nice. Just a bash script. Thanks.
