### ISSUE TITLE
Pasting the URL in the REACT_APP_GRAPHQL_URL variable.

### ISSUE THREAD

**Issue by idkjs** [Volst/new-food-order#21]
What does the "paste the URL in the REACT_APP_GRAPHQL_URL variable" instruction mean? `env.example` already has the default url present. Is this not the URL you are intending to use? 
```s
...
# Frontend
REACT_APP_GRAPHQL_URL=http://localhost:4000
REACT_APP_GRAPHQL_WS=ws://localhost:4466/new-food-order/dev
```

Running the commands `cd backend/ && yarn deploy` produces the following error:
```s
PrisBook:backend$ yarn deploy
yarn run v1.6.0
warning ../../../package.json: No license field
$ prisma deploy && prettier --write 'src/generated/**'
Creating stage dev for service new-food-order !
 ▸    Could not connect to cluster local. Please
 ▸    use docker-compose up -d to start
 ▸    your local Prisma cluster.

```
If you go ahead and open prisma dev tab in Playground this is what you see when trying to hit `http://localhost:4466/new-food-order/dev`

Screenshot:
<img width="1138" alt="screen shot 2018-05-05 at 2 42 52 pm" src="https://user-images.githubusercontent.com/2370391/39663380-c7c0f75a-5072-11e8-8384-cdbffde2eef2.png">

I think i'm missing something in the instructions.

**Comment by SpaceK33z** [comment]
> What does the "paste the URL in the REACT_APP_GRAPHQL_URL variable" instruction mean? env.example already has the default url present. 

Oops, this is not necessary anymore; historically this was used before I switched to Prisma from Graphcool Framework.

> Running the commands cd backend/ && yarn deploy produces the following error:

Did you start up the database like this?

```
cd backend/database
docker-compose up -d
```

If you did and you still get that error, you could start it up with `docker-compose up` (without -d) instead, so all the logging is shown in the foreground. Perhaps that will give you more info as to what's going wrong.

**Comment by idkjs** [comment]
Thanks for the hot debugging tip. Still getting used to docker. So, I think the reason its failing is that the seed mutation is calling a mutation query your probably deleted at some point.

Probably need to change it to signup:
```graphql
mutation {
  signup(
    data: {
      email: "info@volst.nl"
      password: "$2a$10$hACwQ5/HQI6FhbIISOUVeusy3sKyUDhSq36fF5d/54aAdiygJPFzm" # plaintext password: "nooneknows"
      name: "Henk"
    }
  ) {
    token
  }
}
```

**Comment by SpaceK33z** [comment]
Ah, this seed mutation is missing some required fields I recently added. `signup` would not work since this performs a mutation against the Prisma database, not my own service (which exposes "signup" and hides the "createUser" mutation).

I've pushed a possible fix (running low on battery so I'm not starting up Docker 😄)

**Comment by idkjs** [comment]
Too funny, brother. Listen, happy to help with this if you have something you need an extra hand on. Need another set of fingers? Do not hesitate to ask if something comes to mind.

**Comment by idkjs** [comment]
Adding `joinedAt` did not do the trick. email password login dont work. Just an FYI for you. Thanks for talking. I picked up a few techniques. Will keep watching for your updates. Good luck.
